Added ability ot laod a different user profile on the fly

diff --git a/src/launcher/ladmin b/src/launcher/ladmin
--- a/src/launcher/ladmin
+++ b/src/launcher/ladmin
@@ -21,20 +21,17 @@
 # THE SOFTWARE.
 
 INSTALLDIRPLACEHOLDER
-USER_DIR="$HOME/.config/LazyAdmin"
-
-. "$INSTALL_DIR/core/includes.la"
-
+USER_DIR_BASE="$HOME/.config/LazyAdmin"
 
 # In case the user starts ladmin for the first time...
 if [[ "$INSTALL_DIR" != "$HOME/.LazyAdmin" ]]; then
 
 
-  if [[ ! -d "$USER_DIR" ]]; then
+  if [[ ! -d "$USER_DIR_BASE" ]]; then
 
-    mkdir "$USER_DIR"
+    mkdir "$USER_DIR_BASE"
 
-    tar -xvzC "$USER_DIR" -f "$INSTALL_DIR/res/user_files.tar.gz"
+    tar -xvzC "$USER_DIR_BASE" -f "$INSTALL_DIR/res/user_files.tar.gz"
 
 
   fi
@@ -42,5 +39,33 @@ if [[ "$INSTALL_DIR" != "$HOME/.LazyAdmin" ]]; then
 
 fi
 
+
+for (( i=1; i<=$#; i++)); do
+
+    j=$((i+1))
+
+    case "${!i}" in
+
+        "--load-profile") 
+           
+            if [[ -d "$USER_DIR_BASE/${!j}" ]]; then
+
+              userprofile="${!j}"
+
+            else
+              
+              echo 
+              echo "Error: User profile ${!j} not found. Exiting"
+              echo
+              exit 69
+
+            fi
+            ;;
+
+    esac   
+
+done
+
+. "$INSTALL_DIR/core/includes.la"
 
 main "$@"
diff --git a/src/launcher/pladmin b/src/launcher/pladmin
--- a/src/launcher/pladmin
+++ b/src/launcher/pladmin
@@ -21,7 +21,36 @@
 # THE SOFTWARE.
 
 CURRENT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
-USER_DIR="$CURRENT_DIR/user"
+
+userprofile="user"
+
+for (( i=1; i<=$#; i++)); do
+
+    j=$((i+1))
+
+    case "${!i}" in
+
+        "--load-profile") 
+           
+            if [[ -d "$CURRENT_DIR/${!j}" ]]; then
+
+              userprofile="${!j}"
+
+            else
+              
+              echo 
+              echo "Error: User profile ${!j} not found. Exiting"
+              echo
+              exit 69
+
+            fi
+            ;;
+
+    esac   
+
+done
+
+USER_DIR="$CURRENT_DIR/$userprofile"
 CORE_DIR="$CURRENT_DIR/core"
 
 . "$CORE_DIR/includes-port.la"
