Added -p flag as an option for loading user profiles. Also made it possible to load profiles with both absolute and relative paths. Fixed the packaging instructions to exclude "minimal" editions

diff --git a/src/launcher/ladmin b/src/launcher/ladmin
--- a/src/launcher/ladmin
+++ b/src/launcher/ladmin
@@ -22,7 +22,7 @@
 
 INSTALLDIRPLACEHOLDER
 USER_DIR_BASE="$HOME/.config/LazyAdmin"
-userprofile="user"
+userprofile="$USER_DIR_BASE/user"
 
 # In case the user starts ladmin for the first time...
 if [[ "$INSTALL_DIR" != "$HOME/.LazyAdmin" ]]; then
@@ -46,23 +46,43 @@ for (( i=1; i<=$#; i++)); do
     j=$((i+1))
 
     case "${!i}" in
+                
+        "-p" | "--load-profile") 
 
-        "--load-profile") 
-           
-            if [[ -d "$USER_DIR_BASE/${!j}" ]]; then
+            userprofile=""
+            profilename=${!j}       
+            absolutepath=false
 
-              userprofile="${!j}"
+            if [[ ${profilename:0:1} == "/" ]]; then
 
+              absolutepath=true
+            
+            fi
+
+
+            if $absolutepath && [[ -d "$profilename" ]]; then
+      
+              userprofile="$profilename" 
+              
             else
               
+              if [[ -d "$USER_DIR_BASE/$profilename" ]]; then
+
+                userprofile="$USER_DIR_BASE/$profilename"
+                
+              fi
+              
+            fi
+            
+          
+            if [[ -z $userprofile ]]; then
               echo 
-              echo "Error: User profile ${!j} not found. Exiting"
+              echo "Error: User profile $profilename not found. Exiting"
               echo
-              exit 69
+              exit 65
 
             fi
             ;;
-
     esac   
 
 done
diff --git a/src/launcher/pladmin b/src/launcher/pladmin
--- a/src/launcher/pladmin
+++ b/src/launcher/pladmin
@@ -22,7 +22,7 @@
 
 CURRENT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
 
-userprofile="user"
+userprofile="$CURRENT_DIR/user"
 
 for (( i=1; i<=$#; i++)); do
 
@@ -30,27 +30,46 @@ for (( i=1; i<=$#; i++)); do
 
     case "${!i}" in
 
-        "--load-profile") 
-           
-            if [[ -d "$CURRENT_DIR/${!j}" ]]; then
+        "-p" | "--load-profile") 
 
-              userprofile="${!j}"
+          userprofile=""
+          profilename=${!j}       
+          absolutepath=false
 
-            else
+          if [[ ${profilename:0:1} == "/" ]]; then
+
+            absolutepath=true
+          
+          fi
+
+          if $absolutepath && [[ -d "$profilename" ]]; then
+
+            userprofile="$profilename" 
+            
+          else
+            
+            if [[ -d "$CURRENT_DIR/$profilename" ]]; then
+
+              userprofile="$CURRENT_DIR/$profilename"
               
-              echo 
-              echo "Error: User profile ${!j} not found. Exiting"
-              echo
-              exit 69
-
             fi
-            ;;
+            
+          fi
+          
+          if [[ -z $userprofile ]]; then
+            echo 
+            echo "Error: User profile $profilename not found. Exiting"
+            echo
+            exit 65
+
+          fi
+          ;;
 
     esac   
 
 done
 
-USER_DIR="$CURRENT_DIR/$userprofile"
+USER_DIR="$userprofile"
 CORE_DIR="$CURRENT_DIR/core"
 
 . "$CORE_DIR/includes-port.la"
