Version bumped to v3.0alpha. Fixed user defaults for menu heights, closes #57. Changed all variable and constant names to camel_case. Closes #55 and BREAKS COMPATIBILITY with lower versions Current version info is now saved in defaults file.

diff --git a/src/pladmin b/src/pladmin
--- a/src/pladmin
+++ b/src/pladmin
@@ -20,57 +20,47 @@
 # OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 # THE SOFTWARE.
 
-CURRENT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
+CURRENT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
 
-userprofile="$CURRENT_DIR/user"
+user_profile="$CURRENT_DIR/user"
 
-for (( i=1; i<=$#; i++)); do
+for ((i = 1; i <= $#; i++)); do
 
-    j=$((i+1))
+    j=$((i + 1))
 
     case "${!i}" in
 
-        "-p" | "--load-profile") 
+    "-p" | "--load-profile")
 
-            userprofile=""
-            profilename=${!j}       
-            absolutepath=false
+        user_profile=""
+        profile_name=${!j}
+        absolute_path=false
 
-            if [[ ${profilename:0:1} == "/" ]]; then
+        if [[ ${profile_name:0:1} == "/" ]]; then
+            absolute_path=true
+        fi
 
-              absolutepath=true
-            
+        if $absolute_path && [[ -d "$profile_name" ]]; then
+            user_profile="$profile_name"
+        else
+
+            if [[ -d "$CURRENT_DIR/$profile_name" ]]; then
+                user_profile="$CURRENT_DIR/$profile_name"
             fi
 
-            if $absolutepath && [[ -d "$profilename" ]]; then
-      
-              userprofile="$profilename" 
-              
-            else
-              
-              if [[ -d "$CURRENT_DIR/$profilename" ]]; then
+        fi
 
-                userprofile="$CURRENT_DIR/$profilename"
-                
-              fi
-              
-            fi
-
-            if [[ -z $userprofile ]]; then
-            
-              echo 
-              echo "Error: User profile $profilename not found. Exiting"
-              echo
-              exit 69
-
-            fi
-            ;;
-
-    esac   
-
+        if [[ -z $user_profile ]]; then
+            echo
+            echo "Error: User profile $profile_name not found. Exiting"
+            echo
+            exit 65
+        fi
+        ;;
+    esac
 done
 
-USER_DIR="$userprofile"
+USER_DIR="$user_profile"
 CORE_DIR="$CURRENT_DIR/core"
 
 . "$CORE_DIR/includes-port.la"
